version: "3.10"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    ports:
      - 8888:8888
    network_mode: bridge
    volumes:
      - ./.:/scripts
    command: jupyter notebook --ip 0.0.0.0  --port 8888 --no-browser --allow-root
