# Building:
# docker build -t <NAME> -f Dockerfile.notebook .
#
# Running:
# docker run -p 8888:8888 -v $(pwd):/scripts <NAME>

FROM python:3.9

ENV workdir=scripts

RUN mkdir -p /$workdir

WORKDIR /$workdir

COPY . .

RUN pip3 install jupyter --no-cache-dir
RUN pip3 install -r requirements.txt --no-cache-dir

ENV PYTHONPATH "${PYTHONPATH}:/${workdir}"

CMD jupyter notebook --ip 0.0.0.0  --port 8888 --no-browser --allow-root
